Verify manifest version before release

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -6,10 +6,6 @@ on:
     tags:
       - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10
 
-env:
-  PLUGIN_NAME: ${{ github.event.repository.name }}
-  RELEASE_VER: ${{ github.ref }}
-
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -21,7 +17,17 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          TAG_NAME=${RELEASE_VER##*/}
+          PLUGIN_NAME=$(jq -r .id manifest.json)
+          PLUGIN_NAME=${PLUGIN_NAME:-${GITHUB_REPOSITORY##*/}}
+
+          TAG_NAME=${GITHUB_REF##*/}
+          MANIFEST_VERSION=$(jq -r .version manifest.json)
+
+          if [[ "$MANIFEST_VESION" != "$TAG_NAME" ]]; then
+            echo "ERROR: Commit is tagged '$TAG_NAME' but manifest version is '$MANIFEST_VERSION'"
+            exit 1
+          fi
+
           mkdir "${PLUGIN_NAME}"
           assets=()
           for f in main.js manifest.json styles.css; do
@@ -30,5 +36,6 @@ jobs:
               assets+=(-a "$f")
             fi
           done
+
           zip -r "$PLUGIN_NAME".zip "$PLUGIN_NAME"
           hub release create "${assets[@]}" -a "$PLUGIN_NAME".zip -m "$TAG_NAME" "$TAG_NAME"
